### PR TITLE
feat: enable mixin of commands for ctx

### PR DESCRIPTION
**Pull request by carafelix**
Add ability to do, e.g: 
```js
await c.setMyCommands(userCommands, adminCommands)
```
Might be too rudimentary of an implementation?

### CODE REVIEW

**Comment by carafelix** [comment]
I'm pretty sure test are failing because of an http problem. It get's stuck at: Pinging Codecov.

**Comment by roziscoding** [comment]
I'll remove Codecov as a requirement for merge.
I haven't had the time to take a proper look at this yet, but I will ASAP.
Thanks for the PQ!

**Comment by carafelix** [comment]
> I'll remove Codecov as a requirement for merge.
Make sure it's passing tests in local. It's passing on my env, but always better to be sure.

**Comment by roziscoding** [comment]
Hi! Did you test this on runtime too?

**Comment by carafelix** [comment]
Yes. My steps were: 
- verify no type/runtime errors were thrown
- run local test's
- set up an empty bot and verify intended behavoir
- verify cleaning the commands works with 
```await c.setMyCommands(EmptyCommands)```

**Comment by carafelix** [comment]
commit [331b372](https://github.com/grammyjs/commands/pull/12/commits/331b3723a817548e5fd54b650777022dd1acbf7a) condense all the changes.
### Summary
 - #13  is built into this pr
  - Intercepted the setMyCommands function to be able to merge ```SetMyCommandsParams``` from two or more different sources, based on the fact that ```toSingleScopeArgs``` group them by language. Merge function its basically a reducer that concat ```lang.commands``` arrays of the same language. It does not break scoping since it's performed after the ```toSingleScopeArgs``` function. If an empty array is passed, it does not throw, if only one Commands instance is passed it treats it ok.
 -  add info jsdoc info about lang's iso codes (an enum would be ideal :+1: )

**Comment by KnorpelSenf** [comment]
ref #15

**Comment by carafelix** [comment]
Closed because mess up branch management

**Pull request closed without merging**
