### PR TITLE
feat: Add ctx.getNearestCommand using jaro-winkler algorithm

### PR DESCRIPTION
**Pull request by Camelik**
Implement the functionality of acquiring the closest similar command in case of an misspelled command. 

The `.getNearestCommand(commands, ...options)` function has been added to ctx, as it was [suggested](https://github.com/grammyjs/grammY/issues/108#issuecomment-1242180610).

``options: { ignoreCase?: boolean; similarityThreshold?: number; }``

Example of use:

```
import { Bot, Context } from "grammy";
import { Commands, commands, ComandsFlavor } from "@grammyjs/commands

type BotContext = CommandsFlavor & Context;

const bot = new Bot<BotContext>(
    "BOT-TOKEN",
);

const cmds = new Commands();

cmds.command("start", "Initializes bot configuration")
    .localize("pt", "start", "Inicializa as configurações do bot")
    .addToScope(
        { type: "all_private_chats" },
        (ctx) => ctx.reply(`Hello, ${ctx.chat.first_name}!`),
    )
    .addToScope(
        { type: "all_group_chats" },
        (ctx) => ctx.reply(`Hello, members of ${ctx.chat.title}!`),
    );

bot.use(commands());

bot.use(cmds);

bot.on("message::bot_command", (ctx) => {
    const nearestCommand = ctx.getNearestCommand(cmds);

    nearestCommand
        ? ctx.reply(`Did you mean /${nearestCommand}?`)
        : ctx.reply(`This command doesn't exists!`);
});

bot.start()
```

### CODE REVIEW

**Comment by roziscoding** [comment]
This is awesome!
Do you think you could add some tests for the new method, please?

**Comment by Camelik** [comment]
> This is awesome! Do you think you could add some tests for the new method, please?

Yes, done

**Comment by KnorpelSenf** [comment]
This is obviously very cool, I am just not sure if there is enough demand to justify the complexity. But this is more of a strategic decision that I'll leave up to @roziscoding. From a technical point of view, this is pretty awesome!

**Comment by roziscoding** [comment]
I like this, and I think we should go ahead with it, especially since it's opt-in

**Pull request merged**
